name: teste python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: clonar o codigo
      uses: actions/checkout@v4
    - name: instalar o python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: instlar dependencias
      run: |
            python -m pip install --upgrade pip
            pip install pytest
    - name: executar teste
      run: |
        pytest